### ISSUE TITLE
ngWebSocket should be consistent with $http in calling $digest/$apply.

### ISSUE THREAD

**Issue by baalexander** [angular/ngSocket#4]
After receiving data from over the WebSocket, it would be great if the service also called $digest/$apply. At least, similar to what $http is doing.

**Comment by lord2800** [comment]
On the one hand, I agree that symmetry is good. On the other hand, depending on how frequently you pulse data through a socket (think: realtime chat), $digest/$apply might get really expensive for no good reason. Perhaps an option to enable or disable auto $digest?

**Comment by jeffbcross** [comment]
Mr. @btford and I discussed it and think that listeners that handle data from the server should apply by default, but take an options object that can specify autoApply: false. E.g.

``` javascript
mySocket.onMessage(
    function() {...},
    {autoApply: false});
```
