### ISSUE TITLE
ngSocket is not registered with Bower

### ISSUE THREAD

**Issue by begriffs** [angular/ngSocket#5]
I had to point bower at the github repo to install the package.

**Comment by begriffs** [comment]
Also installing with bower pointing at git repo does not include `ngWebSocketBackend`. I'd like to have this as one my my bower `devDependencies` so I can test my angular module that uses websockets.

**Comment by jeffbcross** [comment]
I've fixed the bower issue; not sure what happened there.

Regarding the other issue you mentioned, that was fixed in https://github.com/angular/ngSocket/commit/ea67f7aabb9f6afaf56866830d36264eba7bc694

**Comment by jeffbcross** [comment]
Thank you for raising the issue!
