### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by DracoNoir** [angular/ngSocket#7]
When using the latest code, the following error is reported:

TypeError: Cannot read property 'createWebSocketBackend' of undefined
    at NGWebSocket._connect ...

Upon inspection, it became clear that the ngWebSocketBackend service was not being injected into the function factory.  Changing the function factory line to the following fixes the error:
    factory('ngWebSocket', ['ngWebSocketBackend', function(ngWebSocketBackend) {

**Comment by jeffbcross** [comment]
Fixed here: https://github.com/jeffbcross/ngSocket/commit/ea67f7aabb9f6afaf56866830d36264eba7bc694

Thanks!
